import { useState } from 'react'
import iconClose from '/icon-close.jpg'
import iconMaximize from '/icon-resize.jpg'
import iconMinimize from '/icon-iconize.jpg'

export const RetroOSModal = ({ isOpen, onClose }) => {
  const [isMinimized, setIsMinimized] = useState(false)
  const [isMaximized, setIsMaximized] = useState(false)
  const [position, setPosition] = useState({ x: 0, y: 0 })
  const [isDragging, setIsDragging] = useState(false)
  const [offset, setOffset] = useState({ x: 0, y: 0 })

  const handleMouseDown = (e) => {
    setIsDragging(true)
    setOffset({
      x: e.clientX - position.x,
      y: e.clientY - position.y,
    })
  }

  const handleMouseMove = (e) => {
    if (isDragging) {
      setPosition({
        x: e.clientX - offset.x,
        y: e.clientY - offset.y,
      })
    }
  }

  const handleMouseUp = () => {
    setIsDragging(false)
  }

  if (!isOpen) return null

  return (
    <div
      className='fixed inset-0 z-50 flex justify-center bg-black/30 pt-32'
      onMouseMove={handleMouseMove}
      onMouseUp={handleMouseUp}
    >
      <div
        style={{
          transform: `translate(${position.x}px, ${position.y}px)`,
        }}
        className={`
          absolute
          bg-[#c3c7cb] 
          border-4 
          border-t-white 
          border-l-white 
          border-b-[#808080] 
          border-r-[#808080] 
          shadow-lg 
          w-[500px] 
          ${
            isMinimized
              ? 'h-10 overflow-hidden'
              : isMaximized
              ? 'w-[90%] h-[90%]'
              : 'h-[400px]'
          }
        `}
      >
        {/* Window Header */}
        <div
          onMouseDown={handleMouseDown}
          className='
            bg-[#000080] 
            text-white 
            flex 
            justify-between 
            items-center 
            px-2 
            py-1
            cursor-grab
            active:cursor-grabbing
          '
        >
          <span>About Me:</span>
          <div className='flex space-x-1'>
            <button
              onClick={() => setIsMinimized(!isMinimized)}
              className='p-0 bg-transparent border-none cursor-pointer'
            >
              <img
                src={iconMinimize}
                alt='Minimize icon'
                className='size-4 object-contain'
              />
            </button>
            <button
              onClick={() => setIsMaximized(!isMaximized)}
              className='p-0 bg-transparent border-none cursor-pointer'
            >
              <img
                src={iconMaximize}
                alt='Maximize icon'
                className='size-4 object-contain'
              />
            </button>
            <button
              onClick={onClose}
              className='p-0 bg-transparent border-none cursor-pointer'
            >
              <img
                src={iconClose}
                alt='Close icon'
                className='size-4 object-contain'
              />
            </button>
          </div>
        </div>

        {/* Modal Content */}
        {!isMinimized && (
          <div className='p-4 overflow-auto h-[calc(100%-40px)]'>
            <p>
              A full-stack developer with a passion for creating beautiful and
              functional web applications. I have experience with JavaScript,
              React, Node.js, and more. I am always looking for new //
              opportunities to learn and grow as a developer.
              <br />
              <br />
              (Random text generated by Copilot)
            </p>
          </div>
        )}
      </div>
    </div>
  )
}

// Version without dragging functionality

// import { useState } from 'react'
// import iconClose from '/icon-close.jpg'
// import iconMaximize from '/icon-resize.jpg'
// import iconMinimize from '/icon-iconize.jpg'

// export const RetroOSModal = ({ isOpen, onClose }) => {
//   const [isMinimized, setIsMinimized] = useState(false)
//   const [isMaximized, setIsMaximized] = useState(false)

//   if (!isOpen) return null

//   return (
//     <div className='fixed inset-0 z-50 flex  justify-center bg-black/30 pt-32'>
//       <div
//         className={`
//           bg-[#c3c7cb]
//           border-4
//           border-t-white
//           border-l-white
//           border-b-[#808080]
//           border-r-[#808080]
//           shadow-lg
//           w-[500px]
//           ${
//             isMinimized
//               ? 'h-10 overflow-hidden'
//               : isMaximized
//               ? 'w-[90%] h-[90%]'
//               : 'h-[400px]'
//           }
//         `}
//       >
//         {/* Window Header */}
//         <div
//           className='
//             bg-[#000080]
//             text-white
//             flex
//             justify-between
//             items-center
//             px-2
//             py-1
//           '
//         >
//           <span className='font-serif'>About Me</span>
//           {/* Buttons */}
//           <div className='flex space-x-1'>
//             <button
//               onClick={() => setIsMinimized(!isMinimized)}
//               className='p-0 bg-transparent border-none cursor-pointer'
//             >
//               <img
//                 src={iconMinimize}
//                 alt='Minimize icon'
//                 className='size-4 object-contain'
//               />
//             </button>
//             <button
//               onClick={() => setIsMaximized(!isMaximized)}
//               className='p-0 bg-transparent border-none cursor-pointer'
//             >
//               <img
//                 src={iconMaximize}
//                 alt='Maximize icon'
//                 className='size-4 object-contain'
//               />
//             </button>
//             <button
//               onClick={onClose}
//               className='p-0 bg-transparent border-none cursor-pointer'
//             >
//               <img
//                 src={iconClose}
//                 alt='Close icon'
//                 className='size-4 object-contain'
//               />
//             </button>
//           </div>
//         </div>

//         {/* Modal Content */}
//         {!isMinimized && (
//           <div className='p-4 overflow-auto h-[calc(100%-40px)]'>
//             <p>
//               A full-stack developer with a passion for creating beautiful and
//               functional web applications. I have experience with JavaScript,
//               React, Node.js, and more. I am always looking for new
//               opportunities to learn and grow as a developer. <br />
//               <br /> (Random text generated by Copilot)
//             </p>
//           </div>
//         )}
//       </div>
//     </div>
//   )
// }
